### ISSUE TITLE
No image shown in crowd labelling tool

### ISSUE THREAD

**Issue by AHolliday** [tylin/coco-ui#1]
Hi Tylin,

Thanks for making these tools available.  While playing around with them a bit, I found that all but one of the tools work out-of-the-box.  coco_crowd_labelling.html gives me trouble.  When I open it in my browser, I see the instructional text and the buttons for interacting with an image, but no image to label.  I've attached a screenshot:
![uifail](https://cloud.githubusercontent.com/assets/5325747/14873535/c5018d3e-0d32-11e6-8b37-b9bb7d038e31.png)
I've observed this in both Chrome and Firefox, and on machines running Linux Mint and Ubuntu.

Cheers,
Andrew

**Comment by AHolliday** [comment]
Update: the same issue occurs in Chrome on Windows 7.

**Comment by tylin** [comment]
It runs fine with my Chrome.
Can you report the error message on the console?
Here is how to open chrome console: 
https://developer.chrome.com/devtools/docs/console

Thanks, 
TY

**Comment by AHolliday** [comment]
Here are the error messages produced by Chrome (Version 50.0.2661.86) running on Linux Mint 17.3:

file://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery
coco_crowd_labeling.html:34 Uncaught ReferenceError: $ is not defined
coco_crowd_labeling.html:228 Uncaught ReferenceError: $ is not defined

So it seems that line 4 in the html file:
   `<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>`
is a broken link on our systems, as they try to interpret the path as a path on the local file system, rather than an http path.  Adding "https:" to the start of the path fixes the issue for me:
`<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
`
Let me know if you want me to make a pull request for this change.

**Comment by tylin** [comment]
Fixed!  Thanks for reporting!
